# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8880e37adb11c933181fd6fbaa08d348dc2527ff0857ea81d31e73baf37626b05d64c1944b5690b2b98684869eb0cf76fe5e9afcc677117d2349ae57a2b6376

test:
  secret_key_base: 26d84923924628232ddebcbe0698fd473a7183a1af98708d22502faa4d30464ad5086205c7e287d974d43f3725c1ba7d6db935635f8f13f3ba6c79d2e00ba16e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
